### ISSUE TITLE
error start

### ISSUE THREAD

**Issue by webmobiles** [jferrettiboke/react-auth-app-example#7]
in node 8.1.2

$ npm start

(node:20397) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::4000
    at Object.exports._errnoException (util.js:1016:11)
    at exports._exceptionWithHostPort (util.js:1039:20)
    at Server.setupListenHandle [as _listen2] (net.js:1307:14)
    at listenInCluster (net.js:1355:12)
    at Server.listen (net.js:1455:7)
    at Function.listen (/Users/cherdave/projects/ractgraphredux-app-example/server/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/Users/cherdave/projects/ractgraphredux-app-example/server/src/server.js:32:5)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

**Comment by webmobiles** [comment]
sorry the error was mine, another port was used.
